---
- name: Set hostname and modify /etc/hosts
  hosts: all
  become: true
  serial: 6
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}.{{ domain }}"

    - name: Add my own IP address to /etc/hosts instead localhost
      ansible.builtin.replace:
        path: "/etc/hosts"
        regexp: '^127\.0\.0\.1(\s+){{ inventory_hostname }}(\s+){{ inventory_hostname }}.*'
        replace: "{{ ansible_host }} {{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}"

    - name: Hosts | populate inventory into hosts file
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        block: |-
          {% for item in groups['all'] %}
          {{ hostvars[item]['ansible_host'] }} {{ item }}.{{ domain }} {{ item }}
          {% endfor %}
        state: present
        create: true
        backup: true
        marker: "# Ansible inventory hosts {mark}"
      #when: populate_inventory_to_hosts_file

- name: Chrony installation & configuration
  hosts: all
  become: true
  serial: 6
  roles:
    - { role: chrony, tags: chrony_tag }

#- name: Percona XtraDB cluster installation & configuration
#  hosts: dbs
#  become: true
#  serial: 6
#  roles:
#    - { role: dbs, tags: dbs_tag }

#- name: Ceph cluster installation
#  hosts: cephs,bes
#  become: true
#  serial: 6
#  roles:
#    - { role: ceph_install, tags: ceph_install_tag }

#- name: Ceph cluster configuration
#  hosts: cephs
#  become: true
#  serial: 6
#  roles:
#    - { role: ceph_setup, tags: ceph_setup_tag }

#- name: Web-servers installation & configuration
#  hosts: bes
#  become: true
#  serial: 6
#  roles:
#    - { role: bes, tags: bes_tag }
##    - { role: wordpress, tags: wordpress_tag }

- name: Load Balancer installation & configuration
  hosts: lbs
  become: true
  serial: 6
  roles:
    - { role: lbs, tags: lbs_tag }

#- name: Consul installation & configuration
#  hosts: consuls,lbs,bes
#  become: true
#  serial: 6
#  roles:
#    - { role: consuls, tags: consul_tag }

- name: Filebeat & Node_exporter installation & configuration
  hosts: all
  gather_facts: true
  become: true
  serial: 6
  roles:
    - { role: filebeat, tags: filebeat_tag }
    - { role: node_exporter, tags: node_exporter_tag }

#- name: Opensearch installation & configuration
#  hosts: os_cluster
#  gather_facts: true
#  become: true
#  serial: 6
#  roles:
#    - { role: opensearch, tags: opensearch_tag }

#- name: Opensearch dashboards installation & configuration
#  hosts: dashboards
#  gather_facts: true
#  become: true
#  serial: 6
#  roles:
#    - { role: dashboards, tags: dashboards_tag }

- name: Prometheus & Grafana installation & configuration
  hosts: prometheus
  gather_facts: true
  become: true
  serial: 6
  roles:
    - { role: prometheus, tags: prometheus_tag }

- name: NFTables installation & configuration
  hosts: all
  become: true
  serial: 6
  roles:
    - { role: nftables, tags: nftables_tag }
