---
# dnf install nginx -y
- name: Install nginx
  ansible.builtin.dnf:
    name:
      - nginx
    state: latest

# cp ./nginx/conf.d/upstreams.conf.j2 /etc/nginx/conf.d/upstreams.conf
- name: Template nginx config files
  ansible.builtin.template:
    src: "nginx/{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
  loop:
    - nginx.conf
    - conf.d/upstreams.conf

#- name: Insert line proxy_pass to /etc/nginx/nginx.conf
#  ansible.builtin.lineinfile:
#    path: /etc/nginx/nginx.conf
#    #regexp: '^Listen '
#    insertafter: '^        location / {'
#    line: "{{ item }}"
#  loop:
#    - '                proxy_connect_timeout 5;'
#    - '                proxy_set_header Host $host;'
#    - '                proxy_set_header X-Forwarded-For $remote_addr;'
#    - '                proxy_set_header X-Real-IP $remote_addr;'
#    - '                proxy_pass http://@backend;'

# systemctl enable nginx --now
- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
