---
# systemctl enable nftables --now
- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    enabled: yes

# systemctl enable nginx --now
- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
