---
# After the cluster forms successfully for the first time,
# remove the cluster.initial_master_nodes setting from each nodes' configuration.
- name: Remove `cluster.initial_master_nodes` setting from configuration
  ansible.builtin.command: sed -i '/cluster.initial_master_nodes/d' "{{ os_conf_dir }}/opensearch.yml"

- name: Make sure opensearch is restarted
  ansible.builtin.service:
    name: opensearch
    state: restarted
    enabled: true

- name: Get all the installed ES plugins
  ansible.builtin.command: "{{ os_plugin_bin_path }} list"
  register: list_plugins

- name: Show all the installed ES plugins
  ansible.builtin.debug:
    msg: "{{ list_plugins.stdout }}"

- name: Wait for opensearch to startup
  ansible.builtin.wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    port: "{{ os_api_port }}"
    delay: 5
    connect_timeout: 1
    timeout: 120

- name: Check the opensearch status
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}:9200/_cluster/health?pretty"
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
  register: os_status

- name: Show the opensearch status
  debug:
    msg: "{{ os_status.json }}"
  failed_when: "'number_of_nodes' not in os_status.json"

- name: Verify the roles of opensearch cluster nodes
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}:9200/_cat/nodes?v"
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
  register: os_roles
  run_once: true

- name: Show the roles of opensearch cluster nodes
  debug:
    msg: "{{ os_roles }}"
  run_once: true