---
- name: Include filebeat service
  include_tasks: filebeat.yml
  
#- name: Set hostname
#  ansible.builtin.hostname:
#    name: "{{ inventory_hostname }}"
#  ignore_errors: true

# Disabling for Amazon Linux 2 as selinux is disabled by default.
- name: Configuring the selinux
  ansible.builtin.import_tasks: selinux.yml
  when: inventory_hostname in groups['lbs']

#- name: Populate the nodes to /etc/hosts
#  ansible.builtin.import_tasks: etchosts.yml
#  when: inventory_hostname in groups['lbs']

- name: Tune the system settings
  ansible.builtin.import_tasks: tune.yml
  when: inventory_hostname in groups['lbs']

- name: Include opensearch installation
  ansible.builtin.import_tasks: opensearch.yml
  when: inventory_hostname in groups['lbs']

- name: Include security plugin for opensearch
  ansible.builtin.import_tasks: security.yml
  when: inventory_hostname in groups['lbs']

- name: Include check status opensearch
  ansible.builtin.import_tasks: check.yml
  when: inventory_hostname in groups['lbs']

- name: Include plugin for logstash
  ansible.builtin.import_tasks: logstash.yml
  when: inventory_hostname in groups['lbs']
