---
# systemctl reload nginx
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

# systemctl restart php-fpm # redhat
- name: restart php-fpm redhat
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted
