---
# dnf install chrony -y
- name: Installing chrony
  ansible.builtin.dnf:
    name:
      - chrony
    state: present

# systemctl enable chronyd --now
- name: Start chronyd service
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes

# timedatectl set-timezone Europe/Moscow
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow
  notify: Restart chronyd
