---
# cp gpg.key /root/
- name: Copy the GPG key
  ansible.builtin.copy:
    src: grafana/gpg.key
    dest: /root/

# rpm --import https://rpm.grafana.com/gpg.key
- name: Import the GPG key
  ansible.builtin.rpm_key:
    key: /root/gpg.key
    state: present

# dnf install -y https://dl.grafana.com/oss/release/grafana-10.3.3-1.x86_64.rpm
- name: Grafana | install grafana package
  ansible.builtin.dnf:
    name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.{{ grafana_arch }}.rpm"
    state: present

# systemctl enable --now grafana-server
- name: Grafana | ensure grafana service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana-server
    state: restarted
    enabled: true

