---
- name: Grafana | install grafana package
  ansible.builtin.dnf:
    name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.{{ grafana_arch }}.rpm"
    state: present

- name: Grafana | ensure grafana service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana-server
    state: restarted
    enabled: true

