---
# systemctl enable php-fpm --now
- name: Start php-fpm service
  ansible.builtin.systemd:
    name: "php-fpm"
    state: restarted
    enabled: yes

# systemctl enable nginx --now
- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
